config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
  resources :questions, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    Question.create(question_params)
    redirect_to action: :index
  end

  private
  def question_params
    params.require(:question).permit(:title, :content, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechChat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="header-contents">
        <div class="logo">
          TechChat
        </div>
        <div class="post-button">
          <%= link_to '質問する', new_question_path %>
        </div>
      </div>
    </header>
    
    <%= yield %>
  </body>
</html>

app/views/questions/index.html.erb
<%# 一覧表示画面 %>
<div class='index-main'>
  <div class='post-contents'>
    <% @questions.each do |question| %>
      <%# 投稿１件分の表示 %>
      <div class='post-content'>
        <%# コメントに関する表示 %>
        <div class='comment'>
          <div class='comment__num'>
            0
          </div>
          <div class='comment__unit'>
            comments
          </div>
        </div>

        <%# 質問本文の表示 %>
        <div class='question'>
          <div class='question-top'>
            <div class='question-top__title'>
              <%= question.title %>
            </div>
            <div class='question-top__name'>
              <%= question.name %>
            </div>
          </div>
          <div class='question-bottom'>
            <div class='question-bottom__content'>
              <%= question.content %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/new.html.erb
<div class='new-main'>
  <%# フォーム %>
  <div class='form'>
    <%# フォームのヘッダー表示 %>
    <div class='form-top'>
    </div>

    <%# フォームのメイン部分 %>
    <div class='form-main'>
      <%= form_with model: @question, local: true do |form| %>
        <div class='input-items'>
          <div class='input-items__title'>
            <%= form.text_field :title, placeholder: "タイトル" %>
          </div>
          <div class='input-items__content'>
            <%= form.text_area :content, placeholder: "質問内容" %>
          </div>
          <div class='input-items__name'>
            <%= form.text_field :name, placeholder: "投稿者名" %>
          </div>
          <div class='input-items__submit'>
            <%= form.submit 'POST'%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>